name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18

  test-tf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Setup
        run:  terraform init
      - name: Terraform Validate
        run:  terraform validate
      - name: Lint Terraform
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
          filter_mode: "nofilter"
